# Generated by Django 4.2.2 on 2023-07-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_fav',
            field=models.BooleanField(default=False),
        ),
    ]
