# Generated by Django 4.2.2 on 2023-07-05 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_share', '0002_file_is_fav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='is_fav',
        ),
        migrations.AddField(
            model_name='file',
            name='is_fav',
            field=models.ManyToManyField(related_name='favorite_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
